### ISSUE TITLE
Panel side and links '#!' don't work in WP 8.1

### ISSUE THREAD

**Issue by EmanuelM** [phonon-framework/phonon#107]

**Comment by Qathom** [comment]
Hi @EmanuelM,

Are you using the function `phonon.navigator().changePage(...)` to change the page or the `ontap` event?

Thanks in advance.

**Comment by EmanuelM** [comment]
I use the event `ontap`

I tested panel side now and works fine, my bad

**Comment by Qathom** [comment]
Hi again @EmanuelM ;)

Please, can you try the release **v1.2.4** on Windows Phone.
I normally fixed the `ontap` event thanks to:

* https://patrickhlauke.github.io/touch/tests/results/
* https://blogs.windows.com/buildingapps/2012/11/15/adapting-your-webkit-optimized-site-for-internet-explorer-10/
* and this issue :)

**Comment by EmanuelM** [comment]
No, for me It still doesn't work :(

**Comment by Qathom** [comment]
Hi @EmanuelM,

Sorry for the late reply. Can you give me the output of the following:
			console.log('PHONON EVENTS')
			console.log(phonon.event.start)
			console.log(phonon.event.move)
			console.log(phonon.event.end)
