### ISSUE TITLE
Navigation totally not working on Android 4.2.2 with Webkit 534.30 stock browser

### ISSUE THREAD

**Issue by valkuc** [phonon-framework/phonon#109]
Have checked on Kitchen sink. After clicking on some entry it's not possible to go to any other view. Well this is difficult to explain - in few words - this behavior prevents to use framework at all :( But comparing to other frameworks, Phonon have much smaller footprint and it's very likely for me to use it in my embedded project based on SoC ESP8266. Please tell me if you able to reproduce my problem and how I can help? I will try to record a video later today.

**Comment by John-Henrique** [comment]
@valkuc Please download the [master release ](https://github.com/quark-dev/Phonon-Framework/archive/master.zip) and try again, this was apparently fixed in #105

**Comment by valkuc** [comment]
Did not helped. In firefox all work as expected but in mobile browser navigation did not work. Here is my code:
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
    <link rel="stylesheet" href="/css/phonon.min.css" />
    <title>Example</title>
</head>
<body>
    <div class="side-panel side-panel-left" data-expose-aside="left" data-disable="right" data-page="home" id="home-side-panel">
        <header class="header-bar">
            <button class="btn pull-right icon icon-close show-for-phone-only" data-side-panel-close="true"></button>
            <div class="pull-left">
                <h1 class="title">Menu</h1>
            </div>
        </header>
        <div class="content">
            <ul class="list">
                <li><a class="padded-list" href="#!settings">Settings</a></li>
                <li><a class="padded-list" href="#!system">System</a></li>
            </ul>
        </div>
    </div>

    <home data-page="true">
        <header class="header-bar">
            <button class="btn icon icon-menu pull-left show-for-phone-only" data-side-panel-id="home-side-panel"></button>
            <div class="center">
                <h1 class="title">Главная</h1>
            </div>
        </header>
        <div class="content">
            <div class="padded-full">
                1
            </div>
        </div>
    </home>

    <settings data-page="true">
        <header class="header-bar">
            <button data-navigation="$previous-page" class="btn pull-left icon icon-arrow-back"></button>
            <div class="center">
                <h1 class="title">Настройки</h1>
            </div>
        </header>
        <div class="content">
            <div class="padded-full">
                2
            </div>
        </div>
    </settings>

    <system data-page="true">
        <header class="header-bar">
            <button data-navigation="$previous-page" class="btn pull-left icon icon-arrow-back"></button>
            <div class="center">
                <h1 class="title">Система</h1>
            </div>
        </header>
        <div class="content">
            <div class="padded-full">
                <button class="btn padded-bottom primary" id="btn-reboot">Перезагрузить</button>
            </div>
        </div>
    </system>

    <script src="/js/phonon.min.js"></script>
    <script>
        phonon.options({
            navigator: {
                defaultPage: 'home',
                animatePages: true
            },
            i18n: null
        });

        phonon.navigator().start();
    </script>
</body>
</html>`

Clicking on any item in side menu will open clicked page, but after that you can't go back. If you now refresh page (it have hashtag mark now) it will reload and render correct activity but actually Phonon will think that home page is loaded right now - it will react to side bar defined only for home page. Maybe this is related to https://github.com/quark-dev/Phonon-Framework/issues/107 ?

**Comment by John-Henrique** [comment]
This example is your complete code? Because is missing the action and activity to Phonon... see [Navigator component](http://phonon.quarkdev.com/docs/navigator)

**Comment by valkuc** [comment]
As I understand, the navigation code is optional and for simple navigation between 3 pages defined in same html file it's not necessary. Am I wrong? But then how did it work in Firefox then?

**Comment by valkuc** [comment]
Futhermore, http://phonon.quarkdev.com/App/public/phonon/kitchen-sink/index.html does not work on my device too with same issue - navigation between pages.

**Comment by valkuc** [comment]
Okay, Issue identified. This is caused by enabled "animatePages". If I set this configuration option to false - navigation work, but... there is another issue - menu button stop working. In my example you can notice class "icon-menu" on button in header. So this button stop working after navigation to any page and back.

**Comment by Qathom** [comment]
Hi @valkuc,

Thank you for reporting.
I just tried the kitchen sink on my emulator running Android 4.2.2 and the page animation is working well..
It is probably something else.

`As I understand, the navigation code is optional and for simple navigation between 3 pages defined in same html file it's not necessary. Am I wrong? But then how did it work in Firefox then?`

=> Yes, you are right. It is not mandatory to use page templates (external HTML files).

**Comment by valkuc** [comment]
Yes, it's work in emulator for me too. But on device - no. Looks like browser does not support (does not handle) some CSS3 features used in Phonon. I'm sure this is not related to any JS error, because I have activated developer console and it's clear.

**Comment by Qathom** [comment]
Hi @valkuc,

Sorry for the late reply. Can you give me the output of the following:

``` javascript
console.log('PHONON EVENTS')
console.log(phonon.event.start)
console.log(phonon.event.move)
console.log(phonon.event.end)
```

**Comment by valkuc** [comment]
Hi,
Events are: touchstart, touchmove and touchend.

**Comment by qathom** [comment]
The [Android distribution dashboard](https://developer.android.com/about/dashboards) is now showing that Android 4.2.x is representing 1.5% of running devices.
Hence I close this ticket.
