### ISSUE TITLE
Scroll locks up

### ISSUE THREAD

**Issue by gRegorLove** [phonon-framework/phonon#124]
I'm building a Cordova + Phonon (v1.2.5) app and experiencing scroll lockups similar to #43, except I'm not using tabs. I'm using phonon-core.min.js and forms.min.js

User flow:
1) Category page shows 10 icons (static HTML), scrolling works.
2) Click on a category, list of products is generated dynamically. Usually a pretty long list and scrolling works.
3) Click through to a product, click "Add" button.
4) User is taken to the cart page, list of items in cart is generated dynamically.
5) Clicking the icon to go back to the category page, it usually will not scroll. Sometimes a two-finger scroll works. Usually have to tap between one or two other pages in the app then come back to the category page and it will usually be able to scroll again.

Other information that might be relevant:
- I'm not using tabs. I am using a `<footer>` that is just outside of the `<div class="content">` and contains the four main app icons. The `<footer>` is `position: fixed; bottom: 0; left: 0;`
- I'm using sqllite tables for the database of products and the cart. The pages all load quickly and aren't throwing any javascript errors.
- I'm testing locally on the device using Phonegap Serve. I've experienced the same scroll locking when compiling the app and installing it on the device.

I've tried a bunch of things but can't seem to get it working. Any help would be much appreciated.

**Comment by gRegorLove** [comment]
Actually I can duplicate the scroll locking up just by doing step 1 and 2 described above, then clicking on the Category page again.

I'm not really clear on what `preventClose: false` does, but it's set for every page in the app.

Do I need to do something to "reset" the height of the viewport after dynamic content is added to the DOM?

**Comment by John-Henrique** [comment]
```` preventClose ````
If ```` false ```` do nothing 

if ```` true ```` block close page (get out page), but you need add activity  ```` onClose ````

```` javascript
///... your code
app.on({page: 'home', preventClose: false, readyDelay: 1, content: 'home.html' }, function(activity){
	activity.onClose(function( self ){
	// now I can work what happening
		var active = true; // simple example
		if( ( active != undefined ) && ( active != null ) ){
			self.close();
			phonon.navigator().changePage( "home" );
		}
	});
});

**Comment by gRegorLove** [comment]
Thanks @John-Henrique, that makes a bit more sense. Since I'm using `preventClose: false` and no `onClose` activity, it sounds like that's not a cause of the scroll locking up.

I am using `onCreate` and `onHashChanged` on a couple pages, to attach event listensers to form buttons and load a specific product ID, for example.

**Comment by John-Henrique** [comment]
@gRegorLove man, sometimes scroll lock happening when yours elements no have height, so Phonon can't calculate how many times is necessary to scroll at top or bottom. This help you?

**Comment by gRegorLove** [comment]
I appreciate it, but no it doesn't help much. :) The Category page in step 1 is entirely static HTML, so the height doesn't change. It scrolls fine on first visit. Then visiting a page with dynamic content -- which also scrolls fine -- and back to the Category page, the Category page no longer scrolls.

The dynamic content cannot have an explicit height set on it. I think I'm missing some Phonon core call, like within an `onReady` perhaps, which calculates the height and ensures Phonon knows that. I would think such a call would be automatic within the core, but maybe it's not.

**Comment by gRegorLove** [comment]
In the first page I added an `onReady` that outputs the content's height using `console.log`. On first load, it's 755px and it scrolls. Click to the dynamic list of products, and it scrolls. Click to the first page again, the same height of 755px is logged, but the page won't scroll.

**Comment by gRegorLove** [comment]
More debugging:

1) Category page initial load. on('pageopened') the .content div scrollHeight is 568. Static HTML content with images is definitely taller than that, and the page still scrolls.

2) Tap to another page, intiial load: on('pageopened') the .content divs crollHeight is 652. Static HTML content with images; height measurement appears to be correct, but doesn't scroll.

3) Tap back to the Category page: on('pageopened') the .content div scrollHeight is 1121. This seems more in line with the actual height fo the content, but the page doesn't scroll.

**Comment by gRegorLove** [comment]
@Qathom Could you take a look at this? Thanks!

**Comment by gRegorLove** [comment]
I've now torn out all of the dynamic-height content and explicitly set the min-height of my main content div to 2500px. It should scroll on every single page, and it does intermittently on the first load, but often returning to the same page will make it lock up.

Can someone *please* offer some help?

**Comment by gRegorLove** [comment]
Changing the CSS for .content from `-webkit-overflow-scrolling:touch` to `-webkit-overflow-scrolling:auto` appears to fix it, though obviously doesn't have the momentum scrolling. I'm looking into alternative scrolling solutions to achieve that.

**Comment by Qathom** [comment]
Hi @gRegorLove,

Thank you for reporting this and sorry for the late reply.
Your issue is indeed similar to #43! I only runned some tests on Chrome without Apache Cordova, but it seems that the given CSS rule can "affect" the viewport of the active view.
I think that `.content>*{-webkit-transform:translateZ(0);transform:translateZ(0)}` should be removed. This was a sort of hack to render elements while scrolling on very old browsers.

Please, let me know if this fixes your problem perfectly!

Thanks :)

**Comment by gRegorLove** [comment]
Hi @Qathom, thanks for the confirmation of my suspicions. I've been debugging a lot more in both the Phonegap Serve simulator app as well as compiling with Phonegap Build and running the actual app on the iPod. Removing `.content>*{-webkit-transform:translateZ(0);transform:translateZ(0)}` definitely seemed to help, but I still occasionally got scrolling locked up. Then I turned **off** animatePages and it's working. No more scroll locking up!

This is my first app, so I'm sketchy on some of the details, but I think this might have to do with iOS UIWebView vs WKWebView. I'm pretty sure Phonegap Build is using the former, when the latter is the newer preferred version (probably with better CSS support, transforms, etc.)

I'll keep you posted if I get any more information, or if the bug resurfaces (man, I hope not... this has been quite a frustrating debugging process!). Let me know if you'd like any more information about the development process, if you're interested in duplicating.

**Comment by Qathom** [comment]
Thank you very much @gRegorLove :)

I think `<preference name="DisallowOverscroll" value="true" />` can also improve the scroll event (by default th value is false). (***set to true if you don't want the WebView to rubber-band***).
More information: [iOS Configuration with Cordova](https://cordova.apache.org/docs/en/3.0.0/guide/platforms/ios/config.html).

**Comment by gRegorLove** [comment]
I do have that set to true. I think that was the default when I set up the Phonegap project, but it might have been changed somwehere during all the debugging; I don't remember exactly. :)

**Comment by martinlyder** [comment]
Still an issue on Phonegap/Cordova but for my app only on iPhone 5s. Maby it has to do with the speed the dynamic content is generated.

I'm generating a list of items on the page (aprox 300), I cant scroll, when entering the page. But if i click an item, which opens a fullpanel, then closes the panel again, the scroll works again...

would be great if there was a function that could be called, to reinitiate the scroll heigt when the list is created... or something like that :)

iOS: 11

**Comment by qathom** [comment]
Hello,

This issue is not concerning Phonon directly, but I think I found a fix here: https://github.com/ionic-team/ionic-v1/issues/155

This should solve your issue (see more info from the link above):
```js
var lastY = 0; // Needed in order to determine direction of scroll.
$(".scroll-container").on('touchstart', function(event) {
    lastY = event.touches[0].clientY;
});

$('.scroller').on('touchmove', function(event) {
    var top = event.touches[0].clientY;

    // Determine scroll position and direction.
    var scrollTop = $(event.currentTarget).scrollTop();
    var direction = (lastY - top) < 0 ? "up" : "down";

    // FIX IT!
    if (scrollTop == 0 && direction == "up") {
      // Prevent scrolling up when already at top as this introduces a freeze.
      event.preventDefault();
    } else if (scrollTop >= (event.currentTarget.scrollHeight - event.currentTarget.outerHeight()) && direction == "down") {
      // Prevent scrolling down when already at bottom as this also introduces a freeze.
      event.preventDefault();
    }

    lastY = top;
});
```
