### ISSUE TITLE
Only works with riot+compiler, does not work with precompiled tags

### ISSUE THREAD

**Issue by sbertrang** [phonon-framework/phonon#164]
As I was trying to solve the CSP issue by moving to precompiled tags and riot.csp.js I found out it does not work at the moment:

`Uncaught TypeError: riot.compile is not a function phonon.js:1539`

For now I switched back to riot+compiler and setting 'unsafe-inline' in the CSP tag, but would be nice to have a solution for this. Any ideas?

**Comment by Qathom** [comment]
Hi @sbertrang,

Yes, Riot is supported with the compiler only..
I'll add a Riot feature for using compiled tags.

**Comment by qathom** [comment]
I close this ticket as RiotJS v4 is now available.
An example of use case will be provided with Phonon v1.5.0.
