### ISSUE TITLE
Improve docs "Starter guide"

### ISSUE THREAD

**Issue by John-Henrique** [phonon-framework/phonon#174]
What about change docs of "Starter guide" using examples of "[Guetting started](http://phonon.quarkdev.com/#getting-started)" page? To me "guetting started" page is more util, because I can copy part of codes like other components existent in doc page.

**Comment by qathom** [comment]
Hi @John-Henrique,

I would like to inform you that there have been some substantive changes and your comment has been taken into account in the development of the version 2 documentation and website.
[https://phonon-framework.github.io](https://phonon-framework.github.io)
