### ISSUE TITLE
What about Calendar component?

### ISSUE THREAD

**Issue by John-Henrique** [phonon-framework/phonon#180]
Working here and think why not?! What you think about Phonon with calendar UI? Look that...
![screenshot_20170104-014000](https://cloud.githubusercontent.com/assets/332925/21631143/33667422-d21f-11e6-82f9-940be195f93b.png)

In progress...

- [x] Looking for flexible existent lib
- [x] Testing compatibility with Phonon
- [x] Choose better name
- [x] Custom style sheet
- [ ] Send PR

**Comment by John-Henrique** [comment]
I'm working and need your help.

Wich is better name to component? 
- Datepicker (phonon.datepicker)
- Calendar (phonon.calendar)


@Qathom @mikesten  @andreujuanc  @Gregwar  @psych0pat @oksiquatzel @WietseWind @michaelkoetter

**Comment by Gregwar** [comment]
My opinion: a datepicker is a component that helps you selecting a date while a calendar helps you visualizing schedule
So I guess I'd prefer datepicker here

**Comment by John-Henrique** [comment]
I write my own code, isn't better, but not have dependence of libraries... I think this methods. If you have a better idea, tell me 😉 

**Displaying datepicker**

All you need is add class datepicker to any element.
```
phonon.datepicker();
<div class="datepicker">Auto datepicker</div>
```
Result this
![datepicker-jan](https://cloud.githubusercontent.com/assets/332925/22029445/bdb10442-dcc1-11e6-86ca-47df15a0b6aa.jpg)

You can use ID or CLASS of elements
```
phonon.datepicker( '#myDatepicker' );
<div id="myDatepicker"></div>
```
**Displaying multiple calendars**
You can display multiple datepickers using options.
```
// Init datepicker component
datepicker = phonon.datepicker();

// Previous month (Jan)
datepicker.setLastMonth();

// Actual month (Feb)
datepicker.setMonth();

// Next month (Mar)
datepicker.setNextMonth();
```
Result this
![datepicker-3-months](https://cloud.githubusercontent.com/assets/332925/22029461/cced5690-dcc1-11e6-990b-fb7fe3c47796.jpg)


**You need show 3 next months?**
For what? I don't know, just do it 😅 
```
// Init datepicker component
datepicker = phonon.datepicker();

// Previous month (Jan)
datepicker.setLastMonth();

// Actual month (Feb)
datepicker.setMonth();

// Next month (Mar,Apr and May)
datepicker.setNextMonth(3);
```

**Comment by mikesten** [comment]
I agree with @Gregwar. `datepicker` feels right to me and matches the intent "I want the user to pick a date". 

Incidentally, `<input type="date"/>` should give you a date picker too. PPK wrote a summary of the various browser behaviours yesterday. tldr; it's painful! 
https://medium.com/samsung-internet-dev/making-input-type-date-complicated-a544fd27c45a#.1y870zlur

**Comment by John-Henrique** [comment]
@mikesten I know input type date, time and others new types... but man, you tested in mobile? Each version of SO display a different look... and are so uggly 👎  and not allow to custom.

All work in style of app is broked when using input date... maybe in future be nice but today isn't. My idea is create a visual like the first image in this issue. Is true, exists a lot of scripts and widgets wich give me a datepicker but, look for one flexible and without dependence when working in browser not working in some versions of Android 😯 

PPK quoted a post with several widgets and every using jQuery, Phonon need be agnostic.

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for your initiative! :)
I also find that `datepickers` feels the aim.
Yes, you are right that the `input[type="date"]` is not well supported yet.

**Comment by John-Henrique** [comment]
@Qathom man, I'm in progress slowly but in progress. I have a little question about backdrops (background color) and popups of alert... My idea is create a datepicker but like that of first post, so background need be dark and need a popup, so, is a good idea share class between datepicker and alert.

What you think?


This is actually look
![phonon-datepicker](https://cloud.githubusercontent.com/assets/332925/22623073/153e4522-eb35-11e6-8f21-16765b5ea08f.jpg)

I can pick a date, navigate between months and years, show and hide. Need create a method to get date (from input), change date format.

**Comment by qathom** [comment]
Hi @John-Henrique 

A pull request will be very appreciated to add this component for Phonon v1.
For Phonon v2, there are no plans to add this short-term calendar component.
Therefore, I close this ticket.
Feel free to reopen it if you have any update to share!
