### ISSUE TITLE
Virtual keyboard hiding text fields

### ISSUE THREAD

**Issue by Gregwar** [phonon-framework/phonon#196]
Hello,

It appear that with the current release the virtual keyboard is hiding the fields
I'm not exactly sure but I suppose that the screen is not enough allowed to scroll or overflow to allow this, any idea?

**Comment by John-Henrique** [comment]
This happens every time, to 'resolve' I create an anchor after fields and use setTimeOut to call this anchor. On end page add some space too.

**Comment by Qathom** [comment]
Hi @Gregwar,

Please, can you tell me if :
```xml
<preference name="android-windowSoftInputMode" value="adjustResize"/>
```
fixed your issue?

**Comment by Gregwar** [comment]
No, I had to do the anchor hack to get it fixed

**Comment by qathom** [comment]
This issue does not directly affect Phonon since it is a meta configuration and Phonon does not change these parameters.
Hence I'm closing this ticket.
