### ISSUE TITLE
Routing with Phonon

### ISSUE THREAD

**Issue by Wouter33** [phonon-framework/phonon#217]
Hi Phonon team! Thanks for the awesome project. Looks really cool! 

We're looking into using Phonon as a web version of our Angular hybrid app. Currently i'm wondering if there is any support for using something like UI Router from Angular. 

I'm trying to achieve routes like products/1234 and products/1234/version/134. Is that doable? By connecting it to UI-Router or something else?

**Comment by John-Henrique** [comment]
Sorry, you want use 'products/1234' instead '#!products/1234'?

Otherwise...
Phonon, allow you use '#!products/1234/version/123/whatever/var/vasda/adad' but you need use event `onHashChanged' to get this params, see [navigator](http://phonon.quarkdev.com/docs/navigator).

**Comment by Wouter33** [comment]
The #! doesn't matter. 

Thanks for guiding me in the right direction. How would that example URL map to a page? Let's say i want to have "version" page on products/1234/version/134 and a "details" page on products/1234/details/134.

**Comment by John-Henrique** [comment]
Both cases you need use 'version' and 'details' as parameter. Just try, in your app.js add method 

````
app.on({page: 'product', preventClose: false, content: 'product.html', readyDelay: 1}, function(activity){
	var myparam_1 = null;
	
	activity.onCreate(function(){});
	
	activity.onHashChanged(function( param_1, param_2, param_3  ){
		myparam_1 = param_1;
	        console.log( param_2 );
	});
});
````  Is very simple 👍

**Comment by zhaojunlike** [comment]
But if I want to pass arguments to the content of the configuration?

**Comment by John-Henrique** [comment]
You don't 

content param is used only to set what html document is used for this activity. So you set something like 'page.html' and in your activity you set `onHashChanged` to get params, now you can use params in `onReady`...

```
app.on({page: 'product', preventClose: false, content: 'product.html', readyDelay: 1}, function(activity){
	var param_1 = null;
	
	activity.onCreate(function(){});
	
	activity.onHashChanged(function( param_1, param_2, param_3  ){
		myparam_1 = param_1;
	        console.log( param_2 );
	});

	activity.onReady(function(){
	        console.log( param_1 );
	});

});
```

**Comment by Qathom** [comment]
Hello @Wouter33,

Phonon provides a light and simple router for dealing with this kind of URL **concerning a page**:
`#!/page/value-for-param1/value-for-param2/`

```js
phonon.navigator().on({page: 'mypage', content: 'content.html'}, function (activity) {
    activity.onHashChanged(function(param1, param2) {
        console.log(param1) // value-for-param1
        console.log(param2) // value-for-param2
    })
})
```

Of course, [Angular's router](https://angular.io/docs/ts/latest/guide/router.html) permits you to achieve many things! I don't know what you want to do exactly, but I think that the best thing to do is to just use another complete router if you need to (for example using slot in the path for a route parameter, redirections, etc.).
