### ISSUE TITLE
Phonon + Cordova + IBM MobileFirst Platform

### ISSUE THREAD

**Issue by sureshpathi10** [phonon-framework/phonon#230]
Can anyone help me with any example with Phonon with CORDOVA + IBM Mobilefirst Platform ?

is this even possible?

**Comment by John-Henrique** [comment]
Is very simple. Get look this image example https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/6.3/hello-world/creating-your-first-hybrid-application/

Put Phonon into common folder and call Phonon (CSS and JS) as example http://phonon.quarkdev.com/#getting-started
