### ISSUE TITLE
Accordion Lists not working in UI Components

### ISSUE THREAD

**Issue by martinlyder** [phonon-framework/phonon#238]
The example is working in Docs but not in the UI components view on your homepage... And i cant get it to work in my Phonegap project. Nothing happens when clicking the list items...

**Comment by yoprogramo** [comment]
Same here. Copied the code in a page and nothing happends on click.

**Comment by ckhsu3926** [comment]
Maybe you can show your code :)
In my case the Accordion List works fine .

**Comment by avasilev123** [comment]
Hello,
The example is working fine for me, but I have another issue with accordion list. Nested ones don't act correctly. For example in first nest, the accordion is directly expanded and in the second nest it is with visibility: hidden. Click/tap event does nothing. 
![phonon-nested-accordions-problem](https://user-images.githubusercontent.com/36573122/43687199-ebd57f30-98d9-11e8-93c6-1177c3844bb0.png)

**Comment by qathom** [comment]
Hi all, thanks a lot for reporting this.
This has been fixed.
Hence I close this ticket.
