### ISSUE TITLE
Snap is not defined when use SidePanel component

### ISSUE THREAD

**Issue by kkxlkkxllb** [phonon-framework/phonon#239]
i run pizza-app-with-vue project under examples and add sidePanel component, then get the console error: Uncaught ReferenceError: Snap is not defined

**Comment by hamdallah90** [comment]
+1

**Comment by qathom** [comment]
Thanks for reporting this issue!
This error has been fixed for the latest release v1.5.0.
Hence I'm closing this ticket.
