### ISSUE TITLE
How to select an item by value in popover programmatically?

### ISSUE THREAD

**Issue by dirzhov** [phonon-framework/phonon#252]
Is it possible to select an item by value in popover programmatically. Also to get selected item(with name/value) outside the function onItemChanged.

**Comment by qathom** [comment]
It is now possible with `setActiveItem(...)` and `getActiveItem()` (starting with v1.5.1).
More information regarding this in the docs: https://phonon.quarkdev.com/docs/popovers
Hence I'm closing this ticket.
