### ISSUE TITLE
Installation simplified

### ISSUE THREAD

**Issue by augmen** [phonon-framework/phonon#253]
Please simply the installation Process. Also update your documentation as mots of the Phonegap docs are outdated. Thanks

**Comment by John-Henrique** [comment]
Hey @augmen, you can see how install Phonon in http://phonon.quarkdev.com/, scrool to "Install Phonon" to see sample.

**Comment by qathom** [comment]
Hi @augmen,

Version 1 will soon be depreciated and will only be maintained for bug fixes and minimal improvement of features.
Version 2 is now available: https://phonon-framework.github.io
