### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by Poldan** [phonon-framework/phonon#269]
[http://phonon.quarkdev.com/](http://phonon.quarkdev.com/) has expired.
Maybe, you shall create documentation inside git repository?
Or create full git repository for whole site?

**Comment by Qathom** [comment]
Hi @Poldan,

The website is now up.
I'll create a Github Pages when I have time!

**Comment by qathom** [comment]
Hi @Poldan,

Phonon v2 has now a repository for the website.
Repository: [https://github.com/phonon-framework/phonon-framework.github.io](https://github.com/phonon-framework/phonon-framework.github.io)
Website: [https://phonon-framework.github.io](https://phonon-framework.github.io)
