### ISSUE TITLE
Layout for iphone X

### ISSUE THREAD

**Issue by yoprogramo** [phonon-framework/phonon#277]
I have a problem with iPhone X and Phonon... 

I modified meta headers to avoid white bars (I use fullscreen to remove the upper part, transparent in new ios), but then the header of the page is under the notch, so I tried to add padding to the body, but the left panel does not respect this padding, so I used margings:

`
body.ios {
    margin-top: constant(safe-area-inset-top);
    margin-top: env(safe-area-inset-top);
 }
`

And now it seems everything is pushed down under the notch, buuuut, this means the height of the page is greater than the screen and the user can drag the page up and down (and the device do it when shows the keyboard)

![captura](https://user-images.githubusercontent.com/1540921/34419061-fec74e50-ec01-11e7-9bd9-bb9a9328ac40.png)

So, what can I do?

**Comment by ledarky** [comment]
have you try to add a margin as raw value like 
body.ios .header-bar {
   margin-top: 30px;
}

but find a trick to apply this class only on iphone x devices
for this task you can use phonon natives device's method or this awesome library http://hgoebl.github.io/mobile-detect.js/
