### ISSUE TITLE
Uncaught TypeError: phonon.options is not a function

### ISSUE THREAD

**Issue by amandeeptherockstar** [phonon-framework/phonon#288]
Uncaught TypeError: phonon.options is not a function at app.js:1 & 

index.js:4 An error has occured! You can pen an issue here: https://github.com/quark-dev/Phonon-Framework/issues
(anonymous) @ index.js:4
error (async)
2 @ index.js:3
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
22.../../common/events @ index.js:8
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
24../common/network @ index.js:7
s @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1

What are these two issues
![asdsds](https://user-images.githubusercontent.com/34765485/39955990-aa2218b8-55f5-11e8-83ed-06747b77cd38.png)

**Comment by StoryHack** [comment]
I'm getting the same error. I'm just trying to set up the "Getting Started" demo that is on the front page of the website.

**Comment by StoryHack** [comment]
Ok, so when I pulled the phonon stuff from the zip file download, I got that error. When I used yarn (bower being shuttered and all) to install phonon and then copied away the two files, everything worked. I wonder what the difference is.

**Comment by ChriD** [comment]
on yarn there is the old version which seem to work.. the download is from the master which dont seem to work

**Comment by KingKone** [comment]
same here

**Comment by qathom** [comment]
Hello,

The link to the zip file has been removed.
It is recommended to use npm, yarn or bower to install Phonon.
Please reopen this ticket if you encounter this issue again by providing an example of a code that does not work.
