### ISSUE TITLE
How to start App?

### ISSUE THREAD

**Issue by tauchvogel** [phonon-framework/phonon#289]
I have downloaded the framework and made the steps described on your installation Website. I Putz the App.js file and phonon.js file into my js folder. The CSS is in the CSS folder. In the Source Code I can click the files. Everything is Loaded. But I can not see any color in the header or other content. The pagetwo template is not working.
What is missing?

**Comment by qathom** [comment]
Hello,

The examples have been updated here: https://github.com/phonon-framework/phonon/tree/v1/examples
