### ISSUE TITLE
Question: How to know if the sidebar is open?

### ISSUE THREAD

**Issue by yoprogramo** [phonon-framework/phonon#290]
I have implemented that the back key closes the app if we are on the home page... But I don't want to exit app if the sidebar is open. How do I know if the sidebar is open (check if it is visible doesn't work).

Regards

**Comment by qathom** [comment]
Starting with v1.5.0, it is now possible to get the state with i[sShown()](https://phonon.quarkdev.com/docs/side-panels).
Hence I'm closing this ticket.
