### ISSUE TITLE
Phonon + Vue

### ISSUE THREAD

**Issue by gbtux** [phonon-framework/phonon#298]
Hi 
Try to test Phonon and Vue today. 
1) Clone the v1.4.9
2) cd examples/pizza-app-with-vue
3) npm install
4) npm run dev

 error  in ./node_modules/phonon/dist/css/phonon.css

Module build failed: Error: No PostCSS Config found in: ..../Phonon-Framework-1.4.9/examples/pizza-app-with-vue/node_modules/phonon/dist/css
    at config.load.then (..../Phonon-Framework-1.4.9/examples/pizza-app-with-vue/node_modules/postcss-load-config/src/index.js:55:15)
  
Solution : cf https://stackoverflow.com/questions/49709252/no-postcss-config-found

Create a postcss.config.js in the project root folder with only : 
module.exports = {};

Enjoy with Phonon :)

**Comment by qathom** [comment]
The example has been updated for the latest release 1.5.0.
Hence I'm closing this ticket.
