### ISSUE TITLE
Phonon Version 2 not working (pre-alpha)

### ISSUE THREAD

**Issue by grahn195** [phonon-framework/phonon#300]
Hello.

Version 2 of the framework doesn't work! you get an error message directly

**Comment by qathom** [comment]
Hi @grahn195,

Thank you for your interest in **Phonon v2**!
I still need to refine the website and details before creating the first release.
I'm doing my best to get it out as soon as possible.

Meanwhile, let me know what error message you receive currently and what is your environment (browser, npm version...).

**Comment by qathom** [comment]
Hi @grahn195,

A quick message to inform you that I just released [version 2.0.0-alpha.1](https://phonon-framework.github.io/docs/getting-started/quick-start)!
Please let me know if you're still facing any issue by opening another [issue](https://github.com/phonon-framework/phonon/issues).
