### ISSUE TITLE
How about a 'new icons'?

### ISSUE THREAD

**Issue by John-Henrique** [phonon-framework/phonon#48]
Feel missing of search icon, attach, folder, upload, download, camera, place, navigation, wifi, 
share, contacts and person.

What do you think about add this icons?

example amazing icons
https://design.google.com/icons/

**Comment by Qathom** [comment]
Thank you for your idea, I will add the most used of them! :)

**Comment by martinlyder** [comment]
I'm missing them too ;)

**Comment by John-Henrique** [comment]
Until now no have more icons, but you can add how many you need by using this CSS (use in theme.css or rename theme.css to YOUR-APP.css)

```
.icon-YOURICONNAME:before {
    content:url('../YOURIMGFOLDER/YOUR-IMG-ICON.png');
}
```
Now you can use like this
```
<button class="btn icon icon-YOURICONNAME"></button>
```

**Comment by martinlyder** [comment]
Ok thank you :)
I have installed Material Design icons and use it like this (ex. for search): 
`<button class="btn icon mdi mdi-magnify"></button>`

**Comment by qathom** [comment]
Hi @martinlyder,

Phonon v2 is now available and it has been decided to make some simple icons available with inline SVG.
More info here: [https://phonon-framework.github.io/docs/utilities/icons](https://phonon-framework.github.io/docs/utilities/icons)
Thanks again for opening this issue.
