### ISSUE TITLE
Swipe to Delete (actions) in lists

### ISSUE THREAD

**Issue by John-Henrique** [phonon-framework/phonon#60]
Phonon, need support to swipe events, is very usefull to add actions (delete and other actions) to lists

Maybe a phonon.onSwipe() global event too

**Comment by Qathom** [comment]
A swipe gesture can be added for specific UI components (actions in list). For other purposes, I think it is better to include a swipe library like HammerJS for example.

**Comment by John-Henrique** [comment]
I comment in other issue about swipe slider... but here is more interesting...

In component tabs Phonon use dragend that lib offers support to swipe events... why not abble to use something like ```` javascript phonon.swipe( 'element', function(){}) ````?

**Comment by Qathom** [comment]
I don't see the purpose of this? Is it just for capturing "swipe-start, swipe-end" events or for changing the style of the given element?

**Comment by John-Henrique** [comment]
To allow do thinks like that (of ionic) ![List action](http://www.joshmorony.com/wp-content/uploads/2015/11/delete-example.gif)

**Comment by Qathom** [comment]
Okay, I see.
I allow myself to edit the title of this issue.
I don't have time to check this right now, if you want to make the first version of this release, you're welcome :)

Yes, I think the event management of ***dagend.js*** is nice and indeed, plays well on mobile and desktop browsers.

### An idea

JavaScript side

Create a file named **list-actions.js** with:

Fork ```onStart()```, ```onMove()``` and ```onEnd()```.
Moving .item-actions when swipe is detected on li item.

HTML side
```
<ul class="list">
    <li>
        <a href="#item" class="padded-list">Link</a>
        <ul class="item-actions">
            ...
        </ul>
    </li>
    <li><a href="#item" class="padded-list">Link</a></li>
    <li><a href="#item" class="padded-list">Link</a></li>
</ul>
```

What do you think?

**Comment by John-Henrique** [comment]
Yes, I was thinking something like that. I will do this at night :+1:

**Comment by John-Henrique** [comment]
Trying here and this is my suggest, because, we already class list then, I think need add action to list (ol or li). Now, I want your opinion, to 'buttons actions' we can use class 'btn' as mark to hide swipeable actions, because, all li inside "action" be a 'swipe action'. Are you understand? What you think?

I tried to use Phonon style leaving simple.

```` html
<ul class="list action">
	<li class="divider">List Actions</li>
	<li>
		<a href="#action" class="pull-right btn primary icon icon-star"></a>
		<a href="#action" class="pull-right btn positive icon icon-edit"></a>
		<a href="#action" class="pull-right btn negative icon icon-close"></a>
		<a href="#item" class="padded-list">Link</a>
	</li>
	<li>
		<a href="#action" class="pull-right btn primary"> Other</a>
		<a href="#action" class="pull-right btn positive"> Edit</a>
		<a href="#action" class="pull-right btn negative"> Delete</a>
		<a href="#item" class="padded-list">Link</a>
	</li>
</ul>
```` 

![phonon swipe list action](https://cloud.githubusercontent.com/assets/332925/12112536/50e9dddc-b384-11e5-8922-94619a2798b8.jpg)

**Comment by Qathom** [comment]
Yes, it it better to put buttons inside a ```ul``` element :)
[.buttons already exist for alert dialogs](https://github.com/quark-dev/Phonon-Framework/blob/master/dist/css/phonon.css#L439).

``` html
<ul class="buttons">
    <li><button class="btn primary">Action 1</button></li>
    <li><button class="btn negative">Action 1</button></li>
</ul>
```

**Comment by yoprogramo** [comment]
@John-Henrique Did you make it finally? I mean, the swipe to delete action on phonon?

**Comment by ckhsu3926** [comment]
Hey guys.
I am research this feature and looking for solution.

After some try and failed,
I think

> http://github.com/desandro/draggabilly

is a good solution to build this feature.
It's vary easy to use and won't conflict with tab's dragendjs.

**Comment by qathom** [comment]
I think the best way to manage this feature is to install an additional plugin to make a list of elements (actions) with swipe gestures.
Example of JS library: https://github.com/mishk0/swiped
