### ISSUE TITLE
phonon.alert lock in android 4.1

### ISSUE THREAD

**Issue by leoclaro** [phonon-framework/phonon#92]
I was testing the example of pizza, however when I select the pizza and go to the second page and I click back, cancel, or ask for the lock screen.

Android 4.1

**Comment by John-Henrique** [comment]
@leoclaro What's version of Phonon you tested? [try this](http://phonon.quarkdev.com/App/public/phonon/examples/pizza-app)

**Comment by leoclaro** [comment]
I tried to use the version 1.0.2(last version), build the hybrid app with Cordova. I Used files are available in the **dist folder**.

This link you asked to test is version 1.0.2 or higher? If higher version is to pass the source to test in Cordova?

**Comment by Qathom** [comment]
Hi @leoclaro,

The link is an exemple with the latest relase.
Are you sure that you use the latest release of Phonon?
The current one is **1.1.9**
Please see the "Releases page": [https://github.com/quark-dev/Phonon-Framework/releases](https://github.com/quark-dev/Phonon-Framework/releases)

**Comment by leoclaro** [comment]
I tested version 1.2.0 and continues locking after the close of alert

**Comment by Qathom** [comment]
I am installing the API 16 (Android 4.1.2) and will try it.

**Comment by Qathom** [comment]
Hi @leoclaro, since several months many minor patches have been added.
Can you please tell me if they worked in your situation?

Thanks in advance!

**Comment by AlexKarno** [comment]
I tryed with 1.3.2 without success :(
After call phonon.alert page locked

**Comment by AlexKarno** [comment]
Android 4.2.2

**Comment by AlexKarno** [comment]
[www.zip](https://github.com/quark-dev/Phonon-Framework/files/536210/www.zip)
maybe it can help

**Comment by qathom** [comment]
Hi @AlexKarno,

There are no more recent bugs that have been reported for this problem (current version to date [v1.4.9](https://github.com/phonon-framework/phonon/releases/tag/v1.4.9)).
Also, note that the distribution of Android 4.1.x is now only 1.2% according to [Google's distribution dashboard](https://developer.android.com/about/dashboards).

Hence I close this issue.
