### ISSUE TITLE
Documentation needs improvement. A forum might be required as well.

### ISSUE THREAD

**Issue by LightDye** [phonon-framework/phonon#94]
Great work guys! I'm new to Phonon and Riot but I'm loving both so far. The documentation is a little bit too succinct and I haven't found a space to ask questions about Phonon. I'm tempted to ask questions in StackOverflow, which will give more visibility to your project, but I may not get answers if nobody monitors StackOverflow for Phonon questions, unless they can be linked back to a forum page in Phonon.

Anyway, my specific question today is about the Navigator (http://phonon.quarkdev.com/docs/navigator) a the changePage function. I saw in the documentation that it is possible to pass a parameter to the target page, but how do I read that parameter in the target page, please?

Apologies for hijacking the bug tracker page for asking general questions.

**Comment by John-Henrique** [comment]
@LightDye is very simple, you use activity method of [Navigator](http://phonon.quarkdev.com/docs/navigator) take care to Event callback of table. #onHashChanged

**Comment by LightDye** [comment]
Thanks for pointing that out @John-Henrique, but for a total newbie like me it still wasn't clear enough. After reading the source code of the Navigator I found that the changePage function gets a pageParams which is expected to be a string, which is then appended to the URL. I needed to pass more than one parameter, and I was able to do that by separating them with slashes, like this:

`         var pageParams = foo + '/' + bar + '/' + baz
`
`         phonon.navigator().changePage('target-page', pageParams )
`

Then on the target page I got the values using

`         this.on('hashchanged', function( foo, bar, baz ) {...}
`
That's what I was after and it works. Whether this is the correct way or not, I'm not sure.

**Comment by Qathom** [comment]
Hi @LightDye,

Thank you for reporting this.
I agree with you.
The documentation will be improved as soon as possible.

Concerning your problem, you can pass a parameter like this:
```
phonon.navigator().changePage('page-name', 'my-parameter');
```

Then, for example you can listen to the "pagehash" event.
Example with the following hash: #!page-name/my-parameter

``` javascript
			document.on('pagehash', function(event) {
				console.error('global state pagehash: ' + event.detail.page)
				console.log(event.detail.req[0]); // my-parameter
			})
```

If you do not want to use a global event:

``` javascript
            phonon.navigator().on({page: 'the-page'}, function(activity) {
                activity.onHashChanged(function(myParam) {
                    console.log(myParam); // my-parameter
                });
            });
```

**Comment by LightDye** [comment]
Hi @Qathom. Thank you!

**Comment by qathom** [comment]
Hi @LightDye,

Version 1 will soon be depreciated and will only be maintained for bug fixes and minimal improvement of features.
Version 2 is now available: https://phonon-framework.github.io
Hence I close this ticket.
